build:
  script:
    - source /root/.nvm/nvm.sh > /dev/null 2>&1
    - nvm use stable
    - rbenv global 2.3.0
    - bundle install --deployment --quiet --path /cache
    - rbenv rehash
    - ./deploy
  only:
    - master
